project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "DSCI452"
        contents:
          - index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


